import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type AppLanguage = 'fr' | 'de' | 'en' | 'tr';

const STORAGE_KEY = 'mobile_app_language_v1';

const DICTIONARY: Record<AppLanguage, Record<string, string>> = {
  fr: {
    tab_menu: 'Menu',
    tab_cart: 'Panier',
    tab_orders: 'Commandes',
    tab_profile: 'Profil',
    tab_settings: 'Réglages',
    screen_product: 'Produit',
    screen_checkout: 'Paiement',
    screen_login: 'Connexion',
    screen_signup: 'Inscription',
    screen_forgot: 'Mot de passe oublié',
    screen_reset: 'Réinitialiser',
    settings_title: 'Réglages',
    settings_subtitle: 'Personnalisez votre expérience en toute simplicité.',
    settings_language_title: 'Langue',
    settings_language_hint: 'Choisissez la langue de l’application.',
    settings_help_title: 'Aide & contact',
    settings_help_label: 'Email support',
    settings_help_value: 'alalouche.fr@gmail.com',
    settings_info_title: 'Informations',
    settings_info_app: 'Application',
    settings_info_name: 'Al A Louche',
    settings_info_version: 'Version',
    common_email: 'Email',
    common_password: 'Mot de passe',
    common_phone: 'Téléphone',
    common_full_name: 'Nom complet',
    common_cancel: 'Annuler',
    common_close: 'Fermer',
    common_welcome: 'Bienvenue',
    placeholder_email: 'vous@email.com',
    login_title: 'Connexion',
    login_subtitle: 'Heureux de vous revoir. Connectez-vous pour reprendre votre commande.',
    login_error: 'Impossible de vous connecter pour le moment.',
    login_password_placeholder: 'Votre mot de passe',
    login_loading: 'Connexion...',
    login_cta: 'Se connecter',
    login_create_account: 'Créer un compte',
    login_forgot_password: 'Mot de passe oublié ?',
    signup_title: 'Créer un compte',
    signup_subtitle: 'Rejoignez-nous pour commander plus vite et suivre vos commandes.',
    signup_error: 'Impossible de créer le compte avec ces informations.',
    signup_name_placeholder: 'Votre nom',
    signup_phone_placeholder: 'Votre numéro',
    signup_password_placeholder: 'Choisissez un mot de passe',
    signup_marketing_title: 'Je souhaite recevoir les offres et actualités par email',
    signup_marketing_hint: 'Optionnel. Vous pouvez laisser cette case décochée et créer votre compte normalement.',
    signup_loading: 'Création...',
    signup_cta: "S'inscrire",
    signup_have_account: "J'ai déjà un compte",
    forgot_title: 'Mot de passe oublié',
    forgot_subtitle: 'Entrez votre email et nous vous enverrons les instructions de réinitialisation.',
    forgot_send: 'Envoyer',
    forgot_back_login: 'Retour à la connexion',
    reset_title: 'Réinitialiser',
    reset_subtitle: 'Saisissez le token reçu et choisissez un nouveau mot de passe.',
    reset_token_label: 'Token',
    reset_token_placeholder: 'Code de réinitialisation',
    reset_new_password_label: 'Nouveau mot de passe',
    reset_new_password_placeholder: 'Votre nouveau mot de passe',
    reset_cta: 'Réinitialiser',
    menu_load_error: 'Impossible de charger le menu pour le moment.',
    menu_brand_subtitle: 'French Bistro · Homemade & Seasonal',
    menu_live: 'Menu live',
    menu_items_available: '{count} article(s) disponibles',
    menu_loading: 'Chargement du menu...',
    menu_load_error_title: 'Erreur de chargement',
    menu_unavailable_title: 'Menu indisponible',
    menu_unavailable_copy: 'Aucun article n’est disponible pour le moment.',
    menu_home_selection: 'Sélection maison',
    menu_items_count: '{count} items',
    menu_default_description: 'Préparation maison.',
    menu_brand_name: 'À la Louche',
    product_not_found_title: 'Produit introuvable',
    product_not_found_copy: 'Impossible d’afficher les détails de ce produit.',
    product_back_to_menu: 'Retour au menu',
    product_default_description: 'Préparation maison, faite à la commande.',
    product_required: 'Obligatoire',
    product_optional: 'Optionnel',
    product_single_choice: '1 choix',
    product_multiple_choice: 'Choix multiples',
    product_single_label: 'Choix unique',
    product_multi_label: 'Choix multiple',
    product_finalize_copy: 'Finalisez votre sélection puis ajoutez au panier.',
    product_add_to_cart: 'Ajouter au panier',
    cart_enter_postal: 'Veuillez saisir un code postal de livraison.',
    cart_delivery_unavailable: 'Livraison indisponible pour ce code postal.',
    cart_minimum_missing: 'Minimum CHF {minimum} pour {postal}. Il manque CHF {missing}.',
    cart_promo_cart_changed: 'Le panier a changé. Veuillez réappliquer votre code promo.',
    cart_promo_applied: 'Code promo appliqué.',
    cart_promo_apply_error: 'Impossible d’appliquer ce code promo.',
    cart_promo_removed: 'Code promo retiré.',
    cart_title: 'Panier',
    cart_header_subtitle: '{count} article(s) · prêt en quelques minutes',
    cart_order_type: 'Type de commande',
    order_type_takeaway: 'À emporter',
    order_type_delivery: 'Livraison',
    cart_postal_placeholder: 'Code postal (ex: 1700)',
    cart_zone_ok: 'Zone {postal} · min CHF {minimum} · frais CHF {fee}',
    cart_empty_title: 'Votre panier est vide',
    cart_empty_copy: 'Ajoutez quelques plats depuis le menu pour continuer.',
    cart_unit: 'unité',
    cart_remove: 'Retirer',
    cart_promo_title: 'Code promo',
    cart_promo_placeholder: 'Saisir un code',
    cart_applying: 'Application...',
    cart_apply: 'Appliquer',
    cart_summary: 'Résumé',
    cart_subtotal: 'Sous-total',
    cart_discount: 'Remise',
    cart_continue_checkout: 'Continuer vers le checkout',
    cart_empty_short: 'Votre panier est vide.',
    checkout_back_to_cart: 'Retour au panier',
    checkout_title: 'Paiement',
    checkout_subtitle: 'Finalisez votre commande en quelques secondes',
    checkout_info_title: 'Vos informations',
    checkout_delivery_address: 'Adresse de livraison',
    checkout_delivery_address_placeholder: 'Rue, numéro, ville',
    checkout_order_details: 'Détails commande',
    checkout_type: 'Type',
    checkout_postal_code: 'Code postal',
    checkout_items: 'Articles',
    checkout_promo: 'Promo',
    checkout_total: 'Total',
    checkout_submit: 'Commander maintenant',
    orders_load_error: 'Impossible de charger votre historique pour le moment.',
    orders_status_new: 'Reçue',
    orders_status_accepted: 'Acceptée',
    orders_status_ready: 'Prête',
    orders_status_completed: 'Terminée',
    orders_status_cancelled: 'Annulée',
    orders_status_in_progress: 'En cours',
    orders_title: 'Mes commandes',
    orders_subtitle: 'Suivez l’historique de vos dernières commandes.',
    orders_loading: 'Chargement de vos commandes...',
    orders_oops: 'Oups',
    orders_empty_title: 'Aucune commande pour l’instant',
    orders_empty_subtitle: 'Après votre première commande, vous la retrouverez ici.',
    orders_order: 'Commande',
    orders_thanks: 'Merci pour votre confiance ✨',
    orders_total_paid: 'Total payé',
    profile_title: 'Profil',
    profile_subtitle: 'Votre espace personnel pour gérer votre compte client.',
    profile_updated: 'Profil mis à jour.',
    profile_update_error: 'Mise à jour impossible.',
    profile_delete_error: 'Suppression du compte impossible.',
    profile_hello: 'Bonjour',
    profile_hello_fallback: 'à vous',
    profile_connected: 'Connecté avec votre compte client.',
    profile_delivery_address: 'Adresse de livraison',
    profile_not_set: 'Non renseignée',
    profile_instructions: 'Instructions',
    profile_email_readonly: 'Email (lecture seule)',
    profile_address_line1: 'Adresse ligne 1',
    profile_address_line2: 'Adresse ligne 2',
    profile_address_line2_optional: 'Adresse ligne 2 (optionnel)',
    profile_city: 'Ville',
    profile_delivery_instructions: 'Instructions de livraison',
    profile_delivery_instructions_placeholder: 'Digicode, étage, précisions…',
    profile_account: 'Compte',
    profile_updating: 'Mise à jour du profil…',
    profile_edit: 'Modifier mon profil',
    profile_saving: 'Enregistrement…',
    profile_save: 'Enregistrer',
    profile_logout_hint: 'Vous êtes connecté(e). Vous pouvez vous déconnecter à tout moment.',
    profile_logout: 'Se déconnecter',
    profile_delete_title: 'Supprimer mon compte',
    profile_delete_copy: 'Cette action désactive votre accès client et retire vos informations de profil.',
    profile_delete_cta: 'Supprimer mon compte',
    profile_delete_confirm: 'Confirmez-vous la suppression définitive de votre compte ?',
    profile_deleting: 'Suppression…',
    profile_delete_confirm_cta: 'Confirmer la suppression',
    profile_guest_copy: 'Connectez-vous pour retrouver vos commandes et gérer votre profil.',
  },
  de: {
    tab_menu: 'Menü',
    tab_cart: 'Warenkorb',
    tab_orders: 'Bestellungen',
    tab_profile: 'Profil',
    tab_settings: 'Einstellungen',
    screen_product: 'Produkt',
    screen_checkout: 'Kasse',
    screen_login: 'Anmelden',
    screen_signup: 'Registrieren',
    screen_forgot: 'Passwort vergessen',
    screen_reset: 'Zurücksetzen',
    settings_title: 'Einstellungen',
    settings_subtitle: 'Personalisieren Sie Ihre Erfahrung ganz einfach.',
    settings_language_title: 'Sprache',
    settings_language_hint: 'Wählen Sie die Sprache der App.',
    settings_help_title: 'Hilfe & Kontakt',
    settings_help_label: 'Support-E-Mail',
    settings_help_value: 'alalouche.fr@gmail.com',
    settings_info_title: 'Informationen',
    settings_info_app: 'App',
    settings_info_name: 'Al A Louche',
    settings_info_version: 'Version',
    common_email: 'E-Mail',
    common_password: 'Passwort',
    common_phone: 'Telefon',
    common_full_name: 'Vollständiger Name',
    common_cancel: 'Abbrechen',
    common_close: 'Schließen',
    common_welcome: 'Willkommen',
  },
  en: {
    tab_menu: 'Menu',
    tab_cart: 'Cart',
    tab_orders: 'Orders',
    tab_profile: 'Profile',
    tab_settings: 'Settings',
    screen_product: 'Product',
    screen_checkout: 'Checkout',
    screen_login: 'Login',
    screen_signup: 'Sign up',
    screen_forgot: 'Forgot password',
    screen_reset: 'Reset',
    settings_title: 'Settings',
    settings_subtitle: 'Personalize your experience with ease.',
    settings_language_title: 'Language',
    settings_language_hint: 'Choose the app language.',
    settings_help_title: 'Help & contact',
    settings_help_label: 'Support email',
    settings_help_value: 'alalouche.fr@gmail.com',
    settings_info_title: 'Information',
    settings_info_app: 'App',
    settings_info_name: 'Al A Louche',
    settings_info_version: 'Version',
    common_email: 'Email',
    common_password: 'Password',
    common_phone: 'Phone',
    common_full_name: 'Full name',
    common_cancel: 'Cancel',
    common_close: 'Close',
    common_welcome: 'Welcome',
    placeholder_email: 'you@email.com',
    login_title: 'Login',
    login_subtitle: 'Welcome back. Sign in to continue your order.',
    login_error: 'Unable to sign you in right now.',
    login_password_placeholder: 'Your password',
    login_loading: 'Signing in...',
    login_cta: 'Sign in',
    login_create_account: 'Create an account',
    login_forgot_password: 'Forgot password?',
    signup_title: 'Create account',
    signup_subtitle: 'Join us to order faster and track your orders.',
    signup_error: 'Unable to create your account with this information.',
    signup_name_placeholder: 'Your name',
    signup_phone_placeholder: 'Your phone number',
    signup_password_placeholder: 'Choose a password',
    signup_marketing_title: 'I want to receive offers and news by email',
    signup_marketing_hint: 'Optional. You can leave this unchecked and still create your account.',
    signup_loading: 'Creating...',
    signup_cta: 'Sign up',
    signup_have_account: 'I already have an account',
    forgot_title: 'Forgot password',
    forgot_subtitle: 'Enter your email and we will send reset instructions.',
    forgot_send: 'Send',
    forgot_back_login: 'Back to login',
    reset_title: 'Reset password',
    reset_subtitle: 'Enter your token and choose a new password.',
    reset_token_label: 'Token',
    reset_token_placeholder: 'Reset code',
    reset_new_password_label: 'New password',
    reset_new_password_placeholder: 'Your new password',
    reset_cta: 'Reset',
    menu_load_error: 'Unable to load the menu right now.',
    menu_brand_subtitle: 'French Bistro · Homemade & Seasonal',
    menu_live: 'Live menu',
    menu_items_available: '{count} item(s) available',
    menu_loading: 'Loading menu...',
    menu_load_error_title: 'Loading error',
    menu_unavailable_title: 'Menu unavailable',
    menu_unavailable_copy: 'No items are available right now.',
    menu_home_selection: 'Chef selection',
    menu_items_count: '{count} items',
    menu_default_description: 'House-made preparation.',
    menu_brand_name: 'À la Louche',
    product_not_found_title: 'Product not found',
    product_not_found_copy: 'Unable to display this product details.',
    product_back_to_menu: 'Back to menu',
    product_default_description: 'House-made and prepared to order.',
    product_required: 'Required',
    product_optional: 'Optional',
    product_single_choice: '1 choice',
    product_multiple_choice: 'Multiple choices',
    product_single_label: 'Single choice',
    product_multi_label: 'Multiple choice',
    product_finalize_copy: 'Finalize your selection then add to cart.',
    product_add_to_cart: 'Add to cart',
    cart_enter_postal: 'Please enter a delivery postal code.',
    cart_delivery_unavailable: 'Delivery unavailable for this postal code.',
    cart_minimum_missing: 'Minimum CHF {minimum} for {postal}. CHF {missing} remaining.',
    cart_promo_cart_changed: 'Cart changed. Please re-apply your promo code.',
    cart_promo_applied: 'Promo code applied.',
    cart_promo_apply_error: 'Unable to apply this promo code.',
    cart_promo_removed: 'Promo code removed.',
    cart_title: 'Cart',
    cart_header_subtitle: '{count} item(s) · ready in minutes',
    cart_order_type: 'Order type',
    order_type_takeaway: 'Takeaway',
    order_type_delivery: 'Delivery',
    cart_postal_placeholder: 'Postal code (e.g. 1700)',
    cart_zone_ok: 'Zone {postal} · min CHF {minimum} · fee CHF {fee}',
    cart_empty_title: 'Your cart is empty',
    cart_empty_copy: 'Add a few dishes from the menu to continue.',
    cart_unit: 'unit',
    cart_remove: 'Remove',
    cart_promo_title: 'Promo code',
    cart_promo_placeholder: 'Enter a code',
    cart_applying: 'Applying...',
    cart_apply: 'Apply',
    cart_summary: 'Summary',
    cart_subtotal: 'Subtotal',
    cart_discount: 'Discount',
    cart_continue_checkout: 'Continue to checkout',
    cart_empty_short: 'Your cart is empty.',
    checkout_back_to_cart: 'Back to cart',
    checkout_title: 'Checkout',
    checkout_subtitle: 'Complete your order in a few seconds',
    checkout_info_title: 'Your information',
    checkout_delivery_address: 'Delivery address',
    checkout_delivery_address_placeholder: 'Street, number, city',
    checkout_order_details: 'Order details',
    checkout_type: 'Type',
    checkout_postal_code: 'Postal code',
    checkout_items: 'Items',
    checkout_promo: 'Promo',
    checkout_total: 'Total',
    checkout_submit: 'Place order now',
    orders_load_error: 'Unable to load your history right now.',
    orders_status_new: 'Received',
    orders_status_accepted: 'Accepted',
    orders_status_ready: 'Ready',
    orders_status_completed: 'Completed',
    orders_status_cancelled: 'Cancelled',
    orders_status_in_progress: 'In progress',
    orders_title: 'My orders',
    orders_subtitle: 'Track your recent orders history.',
    orders_loading: 'Loading your orders...',
    orders_oops: 'Oops',
    orders_empty_title: 'No orders yet',
    orders_empty_subtitle: 'After your first order, you will find it here.',
    orders_order: 'Order',
    orders_thanks: 'Thank you for your trust ✨',
    orders_total_paid: 'Total paid',
    profile_title: 'Profile',
    profile_subtitle: 'Your personal space to manage your customer account.',
    profile_updated: 'Profile updated.',
    profile_update_error: 'Update failed.',
    profile_delete_error: 'Account deletion failed.',
    profile_hello: 'Hello',
    profile_hello_fallback: 'there',
    profile_connected: 'Signed in with your customer account.',
    profile_delivery_address: 'Delivery address',
    profile_not_set: 'Not set',
    profile_instructions: 'Instructions',
    profile_email_readonly: 'Email (read-only)',
    profile_address_line1: 'Address line 1',
    profile_address_line2: 'Address line 2',
    profile_address_line2_optional: 'Address line 2 (optional)',
    profile_city: 'City',
    profile_delivery_instructions: 'Delivery instructions',
    profile_delivery_instructions_placeholder: 'Code, floor, details…',
    profile_account: 'Account',
    profile_updating: 'Updating profile…',
    profile_edit: 'Edit profile',
    profile_saving: 'Saving…',
    profile_save: 'Save',
    profile_logout_hint: 'You are signed in. You can log out anytime.',
    profile_logout: 'Log out',
    profile_delete_title: 'Delete my account',
    profile_delete_copy: 'This action disables your access and removes your profile data.',
    profile_delete_cta: 'Delete my account',
    profile_delete_confirm: 'Do you confirm permanent deletion of your account?',
    profile_deleting: 'Deleting…',
    profile_delete_confirm_cta: 'Confirm deletion',
    profile_guest_copy: 'Sign in to find your orders and manage your profile.',
  },
  tr: {
    tab_menu: 'Menü',
    tab_cart: 'Sepet',
    tab_orders: 'Siparişler',
    tab_profile: 'Profil',
    tab_settings: 'Ayarlar',
    screen_product: 'Ürün',
    screen_checkout: 'Ödeme',
    screen_login: 'Giriş',
    screen_signup: 'Kayıt',
    screen_forgot: 'Şifremi unuttum',
    screen_reset: 'Sıfırla',
    settings_title: 'Ayarlar',
    settings_subtitle: 'Deneyiminizi sade bir şekilde kişiselleştirin.',
    settings_language_title: 'Dil',
    settings_language_hint: 'Uygulama dilini seçin.',
    settings_help_title: 'Yardım & iletişim',
    settings_help_label: 'Destek e-postası',
    settings_help_value: 'alalouche.fr@gmail.com',
    settings_info_title: 'Bilgi',
    settings_info_app: 'Uygulama',
    settings_info_name: 'Al A Louche',
    settings_info_version: 'Sürüm',
    common_email: 'E-posta',
    common_password: 'Şifre',
    common_phone: 'Telefon',
    common_full_name: 'Ad Soyad',
    common_cancel: 'İptal',
    common_close: 'Kapat',
    common_welcome: 'Hoş geldiniz',
  },
};

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (next: AppLanguage) => Promise<void>;
  t: (key: string) => string;
  ready: boolean;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('fr');
  const [ready, setReady] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((saved) => {
        if (saved === 'fr' || saved === 'de' || saved === 'en' || saved === 'tr') {
          setLanguageState(saved);
        }
      })
      .finally(() => setReady(true));
  }, []);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: async (next) => {
      setLanguageState(next);
      await AsyncStorage.setItem(STORAGE_KEY, next);
    },
    t: (key) => DICTIONARY[language][key] || DICTIONARY.en[key] || DICTIONARY.fr[key] || key,
    ready,
  }), [language, ready]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
